#include "umutwe.h"

/*
 * generete - a function that generates a random number
 * @mbaduko : a variable to store our random number
 *
 * Return : Random number
 */

int generete(int level)
{
    int mbaduko;

    srand(time(NULL));

    mbaduko = rand() % level;

    // printf("\t%d", mbaduko);

    return (mbaduko);
}

/*
 * Asking - a function that asks user to generate a number
 * @claire : a variable to store our number generated by a user
 *
 * Return : User choosen number
 */

int Asking()
{
    int claire;

    printf("\n\tHey can you enter your guese pls\t:");
    scanf("%d", &claire);

    return (claire);
}

/*
 *  Playing - a function that perfoms the logic behind the game
 * @ i : a variable to hold number that represent the chosen level
 * @ k : a vaeiable to hold the return value of generete function (Random nbr)
 * @ l : a variable to hold the choosen number as return value of Asking function
 * @ ntaga : a variable that gives generete function tha range of number to generete a number from
 * @ inota : update marks after attempting
 * @ intango: initial marks before losing any attempt
 *
 * Return : number of marks after guessing
 */

void playing()
{
    int i, k, l, ntaga, inota, intango;

    printf("\n\n|----------------------------------------------------------------------------------------------------------------------------------------------------------|");
    printf("\n\nHello  in this game there are 3 level available\n\n\t1.Simple level which is ranging from (0 to 10) ------------------> you will press 1 to play this level\n\t2.Intermediate level which is ranging from (0 to 50) ------------> you will press 2 to play this level\n\t3.Difficult level which is ranging from (0 to 100) --------------> you will press 3 to play this level\n\n\tSo which one did u choose to play in -------------------------------------------->\t:");
    scanf("%d", &i);
    printf("\n\n|----------------------------------------------------------------------------------------------------------------------------------------------------------|");

    switch (i)
    {
    case 1:
        ntaga = 10;
        inota = 10;
        break;
    case 2:
        ntaga = 50;
        inota = 50;
        break;
    case 3:
        ntaga = 100;
        inota = 100;
        break;
    default:
        printf("\n\n************************\nInvalid input");
        break;
    }
    intango = inota;
    while (1)
    {

        inota -= 1;
        k = generete(ntaga);
        l = Asking();

        if (l >= ntaga)
        {
            printf("|--------------------------------- Wrong input ---------------------------------|");
        }
        else
        {
            if (k > l)
            {
                printf("\n\n\tToo low bro wangu\n|----------------------------------> The number was %d\n", k);
            }
            else if (k < l)
            {
                printf("\n\n\tToo high bro wangu\n|---------------------------------> The number was %d\n", k);
            }
            else
            {
                printf("\n\n|----------------------------------------------------------------------------------------------------------------------------------------------------------|");
                printf("\n\n\t***************| Wow u made it %d was the rigth one cause is the same as random one\n", k);
                printf("\n\n\t|---------------------------------------------> And out of %d you have %d hhhh!", intango, inota);
                printf("\n\n|----------------------------------------------------------------------------------------------------------------------------------------------------------|");
                break;
            }
        }
    }
}

/*
 * Rounds - a function that call playing function multiple times
 */

void Rounds(int inshuro)
{

    for (int i = 0; i < inshuro; i++)
    {
        printf("\n\t\t\t|--------------------------------Round %d-----------------------------------|", i + 1);
        playing();
    }
}

/*
 * Intro - a function that introduce the game
 * @stra :number of rounds that a user want to play
 *
 * Return : number of waned rounds
 */

int Intro()
{
    int stra;

    printf("\n\t By the way how many rounds do u wish to play\t:");
    scanf("%d", &stra);

    return (stra);
}

/* Enjoy the game wange hhhhhhhhhhhh!
    but in kase u like it you can press *182*1*1 for me*/