#include "umutwe.h"
int main()
{
    int inshuro;

    printf("\n\n\tThis is a classic programming project that is often used to introduce beginners to the basics of programming. \n\tThe goal of the game is to write a program that can guess a secret number that is randomly generated by the computer. \n\tThe user has a limited number of guesses to try to figure out the number.\n\tThis was generated by the sweat and the courage of Mr Ndi ubwo Rurema yamubashishaga\n\n");

    inshuro = Intro();

    if (inshuro > 0)
    {
        if (inshuro > 5)
        {
            while (inshuro > 5)
            {
                printf("\n\t|------------------------------------------------------------->Hhmm mn izo round ni nyinshi 2 basi kina nke 2 then ubone kugaruka sibyo\n\n");
                inshuro = Intro();

                if (inshuro <= 5)
                {
                    Rounds(inshuro);
                }
            }
        }
        else
        {
            Rounds(inshuro);
        }
    }

    return (0);
}

/* Enjoy the game wange hhhhhhhhhhhh!
    but in kase u like it you can press *182*1*1 for me*/